/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import iphone from '../objects/iphone2.gltf';

export default function Iphone2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(iphone)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]} scale={[2, 1, 1]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload(iphone)
